# Generated by Django 2.1.4 on 2019-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_site', '0002_auto_20190505_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='motobike',
            name='image',
            field=models.ImageField(default='', upload_to='bike_images'),
        ),
    ]
