# Generated by Django 2.1.4 on 2019-05-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_site', '0006_auto_20190512_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company_name',
            new_name='company',
        ),
    ]
