# Generated by Django 2.1.4 on 2019-05-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_site', '0009_auto_20190512_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
