# Generated by Django 2.1.4 on 2019-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_site', '0010_auto_20190512_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
    ]
