# Generated by Django 2.1.4 on 2019-05-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_site', '0011_auto_20190512_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='bike_images'),
        ),
    ]
